### PR TITLE
Third Status Indicator for daemon status

### LINKED ISSUE #615: Add a third status bar icon to address the condition when the fapolicyd service is unavailable.
'Unavailable' includes both uninstalled and/or unreachable through the dbus/systemd.

### PR DESCRIPTION
**Pull request by egbicker**
Adds an additional status icon to represent the state where the fapolicyd service is not installed, or is invalid.

This does not indicate whether the fapolicyd application itself is installed, only the fapolicyd systemd service state is reflected.

Closes #615

### CODE REVIEW

**Comment by jw3** [comment]
@egbicker is the valid service check working now?

**Comment by jw3** [comment]
What's the status of this one?

**Comment by egbicker** [comment]
Ready for review, forgot to move it out of draft

**Comment by jw3** [comment]
This looks good.  Found #860 but it is separate issue.

PR needs a description, I'll add one.

**Pull request merged**
