### PR TITLE
CI updates for tools build and node

### LINKED ISSUE #1028: Fix tools CI
The CI for the tools build runs on an older fedora to ensure it links to an older glibc, 2.27. It appears a recent GitHub actions change to node requires 2.28. So we are getting a

`version `GLIBC_2.28' not found`

Two options:
1. bump glibc up to 2.28, which will exclude some older distros
2. checkout manually rather than using the checkout action

If (2) is done, will other actions have issues too?

### LINKED ISSUE #1030: Address Node 20 CI warnings
Most workflows have a warning

> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3, actions/upload-artifact@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

### PR DESCRIPTION
**Pull request by egbicker**
Workflow updates

- increase versions on deprecated actions
- fixes the glibc issue in the tools build

Closes #1028 
Closes #1030

### CODE REVIEW

**Comment by egbicker** [comment]
- actions/checkout@v3->v4
- actions/upload-artifact@v3->v4
- actions/upload-pages-artifact@v2->v3
- actions/download-artifact@v3->v4

**Comment by egbicker** [comment]
https://github.com/actions/upload-artifact/issues/478
upload-artifact upgrade breaks the current CI

**Comment by jw3** [comment]
Could leave upload-artifact at the previous version.

**Comment by jw3** [comment]
The additional artifacts are fine, maybe better this way.

**Pull request merged**
