### PR TITLE
Fixed permissions denied issue when loading toolbar icons

### PR DESCRIPTION
**Pull request by dorschs57**
Wraps the icon loading in exception handling and falls back to the missing icon followed by text button if that can't be loaded.

closes: #573

### CODE REVIEW

**Comment by jw3** [comment]
Did this change the icon size somehow?

Instead of 

image


I am seeing 

image

**Comment by jw3** [comment]
I caused #594 on this branch, doesnt look related to icons, just fyi.

**Review by jw3 — CHANGES_REQUESTED** [review]
#573 is resolved :+1: 

I caused #594 on this branch, it is similar to #573. :-1:

**Comment by dorschs57** [comment]
> Did this change the icon size somehow?
> 
> Instead of
> 
> image
> 
> I am seeing
> 
> image

This should be fixed now.

**Comment by dorschs57** [comment]
> #573 is resolved 👍
> 
> I caused #594 on this branch, it is similar to #573. 👎

I'll look at this in another PR.

**Comment by jw3** [comment]
> I'll look at this in another PR.

Sounds good.

**Review by jw3 — APPROVED** [review]

**Pull request merged**
