### PR TITLE
Add rule file markers to guided rule editor

### LINKED ISSUE #458: Show the file marker for managed editor view of rules
Update the Managed Editor rules view to support displaying the file markers from the `rules.d` directory.

### PR DESCRIPTION
**Pull request by dorschs57**
This adds the rule file marker rows to the table view in the Rules Admin tool's Guided Editor. I'm not sold on the color scheme here, but with adding the collapsible rows for the rule file markers a simple alternating white/light gray pattern didn't look right. 

closes #458

### CODE REVIEW

**Comment by dorschs57** [comment]
Here is my original design with alternating row colors and the darker color for the file marker rows:

image

**Comment by dorschs57** [comment]
@jw3 I think this is what you are talking about.  If we decide to go with this I can see about bumping the file marker text to the left so it lines up with the rule number column.

image

**Comment by jw3** [comment]
> I think this is what you are talking about.

Yes.  I like this better than the previous iteration.

> If we decide to go with this I can see about bumping the file marker text to the left so it lines up with the rule number column.

Yeah doing that could clean it up some more.

**Review by jw3 — APPROVED** [review]

**Comment by dorschs57** [comment]
I updated the styling so the file markers line up better on the left side of the view.

image

**Pull request merged**
