### PR TITLE
Added a refresh button to the Policy Event Analysis Tool

### LINKED ISSUE #311: Remove the All tab until supported
The All perspective tab should be removed until #310 is completed.

### LINKED ISSUE #356: Add a refresh button to the toolbar for the Policy Analysis tool
Add a refresh button to the toolbar that will reload the file in the policy analysis tool. Once reloaded it should restore the view, if possible, to its previous state.  Meaning it should already have the previously selected user/group and previously selected subject loaded.

Relates to #339

### PR DESCRIPTION
**Pull request by dorschs57**
This PR does 3 things:
1. It adds the ability to add buttons to the toolbar dynamically depending on what "tool" is currently being used.
2. Using that it then adds a Refresh button to the toolbar for the Policy Event Analysis tool.  This refresh button will reload the selected log file or the syslog. The refresh will reselect all the users selections in the acl, subject and object views if they are still available for selection after the reload.
3. Finally it removes the unused "All" tab from the acl (Users and Groups) tabs.

closes #356 
closes #311

### CODE REVIEW

**Comment by egbicker** [comment]
I'm seeing an issue with the multi-select context menu:
1. Trust 2 untrusted files to add them to the ATDb
2. Hit the Refresh Button
3. Select the same files, it displays "Trust Files" even though they now show __**AT**__

**Comment by dorschs57** [comment]
> I'm seeing an issue with the multi-select context menu:
> 
> 1. Trust 2 untrusted files to add them to the ATDb
> 2. Hit the Refresh Button
> 3. Select the same files, it displays "Trust Files" even though they now show ****AT****

Good catch @egbicker.  The refresh need to reload the trust database to pick up any changes made by the trust operation performed in step 1.  My last commit should address that issue if you want to retest.

**Comment by egbicker** [comment]
> 

👍 Seems to work now.

**Review by egbicker — APPROVED** [review]

**Review by jw3 — APPROVED** [review]
:+1: Gave it a quick function test in vagrant vm

**Review by tparchambault — APPROVED** [review]
Still testing on FC34.
Can toolbar elements be referred to via a text string, as opposed to an element index? i.e. map/dict vs array/list container? Might not be possible, but easier to maintain/read IMHO.

**Pull request merged**
