### PR TITLE
Change mode to perm in analysis view

### LINKED ISSUE #701: Review the mode column in the analysis view
It never seems to change from **R**WX

### PR DESCRIPTION
**Pull request by egbicker**
Change the 'mode' column to 'perm' in the analysis view.

Also includes updates to the analysis backend to generate the perm string from the logged event.

Closes #701

### CODE REVIEW

**Comment by jw3** [comment]
@egbicker wired up the backend

image

**Comment by jw3** [comment]
Ignore the RPM failures, #745

**Comment by egbicker** [comment]
@jw3 Cleaned up the pytests. Do you want the single word displayed or all the options with the selected one marked up?

**Comment by jw3** [comment]
Single word is good.

**Pull request merged**
