### PR TITLE
Analysis tooltips to describe trust and access

### LINKED ISSUE #646: Tooltip on status indicators in Analysis view
Render the description of the Trust and Access flags to provide context and meaning of the highlighting for a specific Subject / Object.

### PR DESCRIPTION
**Pull request by egbicker**
Adding tooltips to the analysis view to describe trust and access columns

Closes #646

### CODE REVIEW

**Comment by jw3** [comment]
@egbicker need to resolve conflict

**Comment by egbicker** [comment]
@jw3 Missed that, should be taken care of now

**Comment by egbicker** [comment]
@jw3 Missed that, should be good to go

**Review by dorschs57 — APPROVED** [review]
@jw3  I updated the locale strings file. 👍

**Pull request merged**
