### PR TITLE
adding rule ID

### LINKED ISSUE #455: Rule ID in Guided Editor
Render the rule id to the left of the rule text in the guided editor.

### PR DESCRIPTION
**Pull request by egbicker**
Closes #455

### CODE REVIEW

**Comment by jw3** [comment]
The id field is rendered as a `-1` on the info nodes

image

**Comment by egbicker** [comment]
Info node ID issue is fixed

**Comment by jw3** [comment]
I can't test again atm but is it using the rule I'd for the leaf?  I think they should just be implied.

**Comment by egbicker** [comment]
Leaf being the left-hand column?

**Comment by jw3** [comment]
Did that break the sort order?

image

**Comment by egbicker** [comment]
Yeah, the first fix I pushed that broke sorting was to treat the ID like a string so that I could use an empty string display in the child row but Gtk.SortType only has Ascending and Descending

**Comment by jw3** [comment]
LGTM :+1:

**Comment by dorschs57** [comment]
When I have bad rule that generates an error to display I get the error below when I click to expand the child row

image

**Comment by dorschs57** [comment]
The only other thing I see and it can be a later issue to clean up so this can be merged is when I expand the child rows, column 2 seems to bump over some. It causes the table data to "jump" to the right.  Again I wouldn't hold up the merge for that one.

**Comment by dorschs57** [comment]
> When I have bad rule that generates an error to display I get the error below when I click to expand the child row
> 
> image

No longer seeing this issue. Not sure what was causing it but I can't reproduce it.

**Pull request merged**
