### PR TITLE
Add mtime field to trust lists

### PR DESCRIPTION
**Pull request by tparchambault**

### CODE REVIEW

**Comment by tparchambault** [comment]
This PR adds the file's last modification time to both the System and Ancillary trust file lists.

**Comment by jw3** [comment]
I wonder if mtime would be better as the right-most column.

**Comment by tparchambault** [comment]
> I wonder if mtime would be better as the right-most column.

Ha!

**Comment by jw3** [comment]
It is still of less significance than the path in all situations.

**Review by dorschs57 — APPROVED** [review]

**Pull request merged**
