### PR TITLE
Added success message to successful revert operation

### LINKED ISSUE #554: Rollback toaster message
On the "Keep these settings" dialog: if you select "No" or let the timer expire there should be a toaster message that indicates that a rollback occurred.

### PR DESCRIPTION
**Pull request by dorschs57**
closes #554

### CODE REVIEW

**Review by jw3 — COMMENTED** [review]
> Successfully reverted to changes

Was this message the intended message?

**Comment by dorschs57** [comment]
> Was this message the intended message?

Lol that's called being in a hurry to get it out the door. Try that message.

**Comment by dorschs57** [comment]
Since we are holding on #613 do you want me to add in the timeouts for warning messages to this PR?  And, are we happy with the timeout of 10 secs?

**Comment by jw3** [comment]
> do you want me to add in the timeouts for warning messages to this PR

Sure

> are we happy with the timeout of 10 secs?

Make it 5

**Comment by dorschs57** [comment]
> > do you want me to add in the timeouts for warning messages to this PR
> 
> Sure
> 
> > are we happy with the timeout of 10 secs?
> 
> Make it 5

Should be good.

**Pull request merged**
