### PR TITLE
Reorganizing Menus

### LINKED ISSUE #797: Reorganize Menus
Update menus to be
---

### File
- Quit

### Analyze
- Audit Log (disabled state)
- Debug Log
- Syslog

### Tool
- Trust
- Rules
- Profiler

### Session
- Open
- Restore
- Save
- Save As

### Daemon
- Start
- Stop

### Help
- User Guide
- About

### PR DESCRIPTION
**Pull request by egbicker**
Reorganizing the main menu items to be more concise.

Closes #797

### CODE REVIEW

**Review by dorschs57 — CHANGES_REQUESTED** [review]
For me on initial load, the Analyze from Audit Log menu option is grayed out as is the Profiler menu options. Probably some adjustments needed in main_window.py.

**Comment by dorschs57** [comment]
You can cancel the issue with the Profiler menu item. I forgot I need to have that tmp file in place in my dev environment. Not sure why the Analyzer one is disabled though.

**Comment by dorschs57** [comment]
Again my issue. The Audit Log functionality is not completed yet duh. Do we want to hide this menu item until it is?

**Comment by egbicker** [comment]
In the issue John calls it out as an option in a "disabled state" so I added it but I think I lean towards hiding it until we have the functionality

**Comment by dorschs57** [comment]
If its not going to be completed before 1.0 release I'd vote to hide it. Otherwise disabled is good for our pre 1.0.

**Comment by jw3** [comment]
I was on the fence, wanted to see it.  Im good with removing it.

**Review by jw3 — CHANGES_REQUESTED** [review]
Two things

1. move the session menu to the right of daemon
2. rename the menu items under analyze and tool as shown in the issue description

**Review by jw3 — APPROVED** [review]
:+1:

**Pull request merged**
